/**
 * 全局主题配置
 * 定义应用程序的颜色、间距、阴影等主题变量，使用CSS变量
 */

export const theme = {
  colors: {
    primary: {
      light: 'var(--color-primary-light)',
      DEFAULT: 'var(--color-primary)',
      dark: 'var(--color-primary-dark)',
    },
    secondary: {
      light: 'var(--color-secondary-light)',
      DEFAULT: 'var(--color-secondary)',
      dark: 'var(--color-secondary-dark)',
    },
    background: {
      light: 'var(--color-background-light)',
      dark: 'var(--color-background-dark)',
    },
    text: {
      light: 'var(--color-text-light)',
      dark: 'var(--color-text-dark)',
    },
    gray: {
      50: 'var(--color-gray-50, #F9FAFB)',
      100: 'var(--color-gray-100, #F3F4F6)',
      200: 'var(--color-gray-200, #E5E7EB)',
      300: 'var(--color-gray-300, #D1D5DB)',
      400: 'var(--color-gray-400, #9CA3AF)',
      500: 'var(--color-gray-500, #6B7280)',
      600: 'var(--color-gray-600, #4B5563)',
      700: 'var(--color-gray-700, #374151)',
      800: 'var(--color-gray-800, #1F2937)',
      900: 'var(--color-gray-900, #111827)',
    },
  },
  spacing: {
    px: 'var(--spacing-px)',
    0: 'var(--spacing-0)',
    0.5: 'var(--spacing-0-5)',
    1: 'var(--spacing-1)',
    1.5: 'var(--spacing-1-5)',
    2: 'var(--spacing-2)',
    2.5: 'var(--spacing-2-5)',
    3: 'var(--spacing-3)',
    3.5: 'var(--spacing-3-5)',
    4: 'var(--spacing-4)',
    5: 'var(--spacing-5)',
    6: 'var(--spacing-6)',
    7: 'var(--spacing-7)',
    8: 'var(--spacing-8)',
    9: 'var(--spacing-9)',
    10: 'var(--spacing-10)',
    11: 'var(--spacing-11)',
    12: 'var(--spacing-12)',
    14: 'var(--spacing-14)',
    16: 'var(--spacing-16)',
    20: 'var(--spacing-20)',
    24: 'var(--spacing-24)',
    28: 'var(--spacing-28)',
    32: 'var(--spacing-32)',
    36: 'var(--spacing-36)',
    40: 'var(--spacing-40)',
    44: 'var(--spacing-44)',
    48: 'var(--spacing-48)',
    52: 'var(--spacing-52)',
    56: 'var(--spacing-56)',
    60: 'var(--spacing-60)',
    64: 'var(--spacing-64)',
    72: 'var(--spacing-72)',
    80: 'var(--spacing-80)',
    96: 'var(--spacing-96)',
  },
  borderRadius: {
    none: 'var(--radius-none)',
    sm: 'var(--radius-sm)',
    DEFAULT: 'var(--radius)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    xl: 'var(--radius-xl)',
    '2xl': 'var(--radius-2xl)',
    '3xl': 'var(--radius-3xl)',
    full: 'var(--radius-full)',
  },
  typography: {
    fontFamily: {
      sans: 'var(--font-family-sans)',
      serif: 'var(--font-family-serif)',
      mono: 'var(--font-family-mono)',
    },
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '3.75rem',
      '7xl': '4.5rem',
      '8xl': '6rem',
      '9xl': '8rem',
    },
    fontWeight: {
      thin: '100',
      extralight: '200',
      light: '300',
      normal: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
      extrabold: '800',
      black: '900',
    },
    lineHeight: {
      none: '1',
      tight: '1.25',
      snug: '1.375',
      normal: '1.5',
      relaxed: '1.625',
      loose: '2',
    },
  },
  breakpoints: {
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
    '2xl': '1536px',
  },
  shadows: {
    sm: 'var(--shadow-sm)',
    DEFAULT: 'var(--shadow)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
    xl: 'var(--shadow-xl)',
    '2xl': 'var(--shadow-2xl)',
    inner: 'var(--shadow-inner)',
    none: 'var(--shadow-none)',
  },
  zIndex: {
    0: 0,
    10: 10,
    20: 20,
    30: 30,
    40: 40,
    50: 50,
    auto: 'auto',
  },
  transitions: {
    DEFAULT: 'var(--transition)',
    fast: 'var(--transition-fast)',
    slow: 'var(--transition-slow)',
  },
} as const;

export type Theme = typeof theme;

export default theme; 